[package]
name = "testing"
version = "0.1.0"
edition = "2024"

[dependencies]
bees = { path = "../bees"}
dotenvy = "0.15.7"
tokio = "1.48.0"
reqwest = "0.12.24"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
async-trait = "0.1.89"

[profile.release]
opt-level = 3